name: Hourly Looper


on:
    schedule:
      - cron: "0 * * * *"
    push:
      branches: [ main ]
    workflow_dispatch:

env:
  API_HASH: {{ secrets.API_HASH }}
  API_ID: {{  secrets.API_ID }}
  BOT_TOKEN: {{ secrets.BOT_TOKEN }}
  REDIS_ENDPOINT: {{ secrets.REDIS_ENDPOINT }}
  REDIS_PASS: {{ secrets.REDIS_PASS }}
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v2
       - uses: styfle/cancel-workflow-action@0.9.0
         name: "Cancel duplicate workflow runs"
         with:
            all_but_latest: true
            access_token: ${{ github.token }}
       - name: Set up Python 3.9
         uses: actions/setup-python@v2.2.2
         with:
           python-version: 3.9          
       - name: Building
         continue-on-error: true
         run: |
           sudo apt -qq update && sudo apt -qq install -y --no-install-recommends
           git clone https://github.com/Zackbloodshot/SN.git && cd SN && pip3 install -r requirements.txt
       - name: Looping
         timeout-minutes: 350
         continue-on-error: true
         run: |
           pwd
           cd SN
           echo environment loaded!
           python3 -m Sagiri_Notifs
#       - name: Loop workflow
#         continue-on-error: true
#         run: |
#           git clone https://github.com/${GITHUB_REPOSITORY} loop
#           cd loop || exit 1
#           echo $(date -u +%T%P) >> loop.txt
#           git add loop.txt
#           git commit -m "Workflow : Loop $(date -u +%D-%T%P)"
#           git push -q https://${{ secrets.TOKEN }}@github.com/${GITHUB_REPOSITORY} HEAD:main
